### ISSUE TITLE
Test Payload Issue

### ISSUE THREAD

**Issue by peter-murray** [peter-murray/issue-body-parser-action#1]
This is a JSON payload

```json payload
{
  "name": "payload",
  "version": "1.0.0"
}
```

A standard JSON code block
```json
{
  "name": "IS NOT PAYLOAD"
}
```

Some YAML encoded data
```yaml
yaml_payload:
  name: A YAML payload
  version: 2.0.0
```
